const expoConfig = require('eslint-config-expo/flat');

module.exports = [
  ...expoConfig,
  {
    // `api/` is generated by scripts/build-api.mjs — minified bundles, not source.
    ignores: ['dist/*', 'dist-api/*', 'api/*', 'node_modules/*', '.expo/*'],
  },
];
